split off renovate job (#6)
* split off renovate job

* insert variable struct

* rename job

* fix variable assignment

* fix variable names

* add version / branchname

* fix/add on parameter for reusable workflow

* use action instead of workflow

* Revert "use action instead of workflow"

This reverts commit 032c5cf3c52423b09f8e69056c25d0b06c90a3a3.

* change trigger of reusable workflow from call to dispatch

* test: remove input parameter to check if i can trigger job manually

* add push as execution trigger

* change on to workflow call of reusable workflow

* add input paramter for filter again

* add apax token to interface

* us of setting secrets: inherit

* fix variable assginment

* fix assignment of variable

* change quotation marks

* change branch to main

* adapte struct for documentation

* docs: trigger event

* add paramter describtion

* remove braces

* repair shortcut

* add hint for autodiscoverFilter

* Incorporate review findings

* Incorporate review findings

* Incorporate review findings

* Add file extension

* restructure readme

* apply co-pilot suggestions

* docs: more workflows

---------

Co-authored-by: Thomas Drosdzoll <thomas.drosdzoll@siemens.com>

diff --git a/.github/workflows/trigger-renovate-automatically.yml b/.github/workflows/trigger-renovate-automatically.yml
--- a/.github/workflows/trigger-renovate-automatically.yml
+++ b/.github/workflows/trigger-renovate-automatically.yml
@@ -1,6 +1,13 @@
-name: renovate
+name: automatic-renovate-bot-trigger
+
 on:
-  workflow_dispatch: # by change adapt readme
+  workflow_call:
+    inputs:
+      renovate_repository_filter:
+        description: 
+          "This fills the setting autodiscoverFilter of renovate. The name of the repository from which the job was called should be written here, according to the scheme 'simatic-ax/repository_name'"
+        required: true
+        type: string
 
 jobs:
   renovate:
@@ -18,10 +25,11 @@ jobs:
         run: |
           apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.GITHUB_TOKEN }}"
 
-      - name: install_apax
+      - name: install_apax_and_set_variables
         shell: bash
         env:
           APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
+          RENOVATE_REPOSITORY_FILTER: ${{ inputs.renovate_repository_filter }}
         run: |
           curl -H "Authorization: Bearer $APAX_TOKEN" "https://api.simatic-ax.siemens.io/apax/login?format=npmrc" -o .npmrc
           # Store the npmrc file in the RENOVATE_NPMRC variable so that it can be used in the next step:
@@ -30,11 +38,20 @@ jobs:
             cat .npmrc
             echo EOF
           } >> "$GITHUB_ENV"
+          # Store the value of '' in globale variable RENOVATE_AUTODISCOVERFILTER, that is used in renovate-global-config.js om next step:
+          echo "RENOVATE_AUTODISCOVERFILTER=$RENOVATE_REPOSITORY_FILTER" >> "$GITHUB_ENV"
+          
           # Mask the contents of the npmrc file so that they don't appear in job logs:
-          while read -r line;
-          do
-            echo "::add-mask::${line}"
-          done < .npmrc
+          if [ -f .npmrc ]; then
+            while IFS= read -r line || [ -n "$line" ]; do
+              if [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
+                echo "::add-mask::${line}"
+              fi
+            done < .npmrc
+          else
+            echo "Error: .npmrc file not found" >&2
+            exit 1
+          fi
 
       - name: Self-hosted Renovate
         uses: renovatebot/github-action@v39.1.1
